### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by mbdemoraes** [cicirello/Chips-n-Salsa#37]
I could download and build the library using the makefile. However, when I tried to run "make examples", I got the following error:

```
java -cp "exbin;dist/chips-n-salsa-1.0-jar-with-dependencies.jar" org.cicirello.examples.chipsnsalsa.BitVectorExample
Error: Could not locate or load main class org.cicirello.examples.chipsnsalsa.BitVectorExample
Caused by: java.lang.ClassNotFoundException: org.cicirello.examples.chipsnsalsa.BitVectorExample
make: *** [Makefile:11: examples] Error 1
```
The same error appears when I try to run each example manually. I'm running the commands from the root repository.

cc openjournals/joss-reviews#2448

**Comment by cicirello** [comment]
@mbdemoraes Are you sure that the build was successful?  Can you check if the exbin directory was created (which is where the class files for the examples will be)?  I get that error if I run `make examples` without having executed the build.  Also, `make examples` by itself doesn't execute the build (there isn't really a good way in make to have that target in make dependent upon the build).

**Comment by mbdemoraes** [comment]
Hey @cicirello ! Yeah, the build was successful and exbin directory was created. It seems every class is in there (BitVectorExample, CustomIntegerCostProblemExample, etc.). 

I tried to download the library again, on another directory and did again the build process. Also, I tried to do a `make clean` and rebuild (with success), but in both cases I have the same issue.

**Comment by cicirello** [comment]
@mbdemoraes I was able to recreate the makefile bug on Ubuntu.  I noticed that I had a semicolon as delimiter rather than a colon in the classpath when running the examples, so it worked on Windows, but not on Linux (or probably any other OS other than Windows). I have the makefile checking the OS now so should work on any OS.  Can you confirm that it works for you now?  Don't want to close issue yet in case there is something else hiding in the Makefile.  It now works for me on both Ubuntu and Windows.

**Comment by mbdemoraes** [comment]
@cicirello thank you for your modification! I forgot to say that I was using Lubuntu (an Ubuntu-based distribution), I'm sorry. But now it works fine.
