### ISSUE TITLE
Other libraries?

### ISSUE THREAD

**Issue by nnadeau** [cicirello/Chips-n-Salsa#6]
The paper includes a lot of discussions around algorithms (the first section) and the library itself (the second section). What about other (i.e., competitor) libraries? I highly doubt that this is the only library that serves this purpose for Java. What about for other languages? How does this work compare to those implementations?

cc https://github.com/openjournals/joss-reviews/issues/2448

**Comment by cicirello** [comment]
@nnadeau  I think I've addressed all of your feedback so far.  To see the pdf of the current version of the paper, use the preview service (https://whedon.theoj.org/). The whedon pdf generator is giving a weird error that they are investigating if generated from in the review issue, but it generates fine from the preview service.  Error appears related to something in the review issue itself, rather than the paper.
