### ISSUE TITLE
BUG: CI build silently fails to generate coverage reports

### ISSUE THREAD

**Issue by N-Wouda** [cicirello/Chips-n-Salsa#703]
**Describe the bug**

The coverage report in the CI fails silently:
![image](https://github.com/cicirello/Chips-n-Salsa/assets/16272507/20a8e864-579b-4221-a8f8-1124bcf17c12)

**Comment by cicirello** [comment]
The permissions for the `GITHUB_TOKEN` aren't able to comment on pull requests from forks, under most circumstances (e.g. it can if I rerun the workflow). It's a GitHub Actions security thing. I have silent failures for that step of workflow on purpose to avoid GitHub Actions failing workflow runs on pull requests due to just that, mainly for PRs from dependabot which are the only ones that will automatically cause workflow to run. I have things set to require approval for workflow runs for PRs from outside contributors. In those cases, once I approve the run, the Actions token is able to comment on the PR.

The coverage report itself is actually generated and saved as a workflow artifact, which you should be able to find via the Actions tab. You can also find it if you build locally (`mvn clean package -P coverage`) in the `target/site` directory.

I don't see a PR from you so I'm assuming you ran the build workflow within a fork or clone. So there might be additional token permissions issues beyond PR commenting (GitHub has default token permissions locked down quite a bit).

**Comment by N-Wouda** [comment]
Alright, thanks for the explanation!

**Comment by cicirello** [comment]
@N-Wouda you're welcome
